---
# - name: config | Configuring GitLab Runner
#   template:
#     src: "etc/gitlab-runner/config.toml.j2"
#     dest: "/etc/gitlab-runner/config.toml"
#   register: "gitlab_runner_configured"
#   notify:
#     - "restart gitlab-runner"

- name: config | Listing Registered GitLab Runners
  command: "gitlab-runner list"
  register: "gitlab_runners"
  changed_when: false

- name: config | Register GitLab Runner
  command: "gitlab-runner register -n -u {{ gitlab_runner_config.url }} -r {{ gitlab_runner_config.token }} --executor {{ gitlab_runner_config.executor }}"
  when: ansible_hostname not in gitlab_runners.stdout
